"""Add ohlcv_cache table

Revision ID: 1d7dcca6845c
Revises: d9e3f2a1b4c0
Create Date: 2026-03-28 18:20:49.710793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7dcca6845c'
down_revision: Union[str, Sequence[str], None] = 'd9e3f2a1b4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_address', sa.String(length=42), nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=False),
    sa.Column('network', sa.String(length=10), nullable=False),
    sa.Column('start_ts', sa.Integer(), nullable=False),
    sa.Column('end_ts', sa.Integer(), nullable=False),
    sa.Column('candles_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_address', 'token_address', 'network')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ohlcv_cache')
    # ### end Alembic commands ###
