"""Add receipt_cache table

Revision ID: a6019f7a913a
Revises: 0301b0a4a1e7
Create Date: 2026-03-21 04:59:01.661750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6019f7a913a'
down_revision: Union[str, Sequence[str], None] = '0301b0a4a1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('logs_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'tx_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_cache')
    # ### end Alembic commands ###
