"""Add is_profitable to transactions

Revision ID: e4ae7ea277b4
Revises: 592d43212266
Create Date: 2026-03-28 19:23:59.197162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ae7ea277b4'
down_revision: Union[str, Sequence[str], None] = '592d43212266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_profitable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_profitable')
    # ### end Alembic commands ###
